### ISSUE TITLE
Password is hard-coded at one occasion in index.php

### ISSUE THREAD

**Issue by MatthiasKauer** [PhilippMundhenk/NoFrillsPhotoSharing#1]
Hi,
in one line $password is not compared to $expected_pass.

```
if($password !== 'password')
{
    $passError = 'Invalid Password';
}
```

Looks like a bug to me.

PS: Yes, I was checking whether you had left the real password there somewhere ;)

**Comment by PhilippMundhenk** [comment]
This is "fixed" now.
Clearly a hard-coded password in a large functional file is not good. This is not the final stage of the project. I will push that into a config file some day.
